apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dbpassword11
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: movies-dbcreation-script 
          mountPath: /docker-entrypoint-initdb.d
  
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: ebs-mysql-pv-claim
  - name: movies-dbcreation-script
    configMap:
      name: movies-dbcreation-script 
