apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

  nfs:
    path: /dir/path/on/nfs/server
    server: ip-nfs-server

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
spec:
  storageClass: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


