apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymodel-serving
  labels:
    app: mymodel
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mymodel
  template:
    metadata:
      labels:
        app: mymodel
    spec:
      containers:
      - name: mymodel-serving
        image: public.ecr.aws/f6e8d9s2/model:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata: 
  name: mymodel-serving
spec:
  ports:
  - port: 8501
    nodePort: 30111
  selector: 
    app: mymodel
  type: NodePort